[[language]]
name = "php"
language-servers = [ "intelephense" ]

[language-server.intelephense.config]
licenceKey = "xxxxx"

# [language-server.phpactor]
# command = "phpactor"
# args = [ "language-server" ]
